### PR TITLE
Employee's first commit

### PR DESCRIPTION
**Pull request by RajatGupta0705**
Hi.
Committed the first change

### CODE REVIEW

**Comment by RajatGupta0705** [comment]
Hi,
Please add the Range Prime Number Class

**Comment by SaurabhGupta0705** [comment]
Hi,
Please add the range prime number class

**Comment by RajatGupta0705** [comment]
Added the suggested change

**Comment by SaurabhGupta0705** [comment]
The changes look good. Merging into master

**Pull request merged**
